id: PE34E2A4E
initial_creation_type: input
source_metadata:
  title: Khyenrab Chökyi Özer Series
  language: bo
  description: Texts by and about the learned Sakya scholar Khyenrab Chökyi Özer (mkhyen
    rab chos kyi 'od zer, 1889–1959), the student of Khenpo Shenpen Nangwa and his
    successor at the scriptural colleges of both Dzongsar and Palpung.
  volume:
    a8c65bd2d8084787b42f441292df480e:
      title: Advice on Remembering One’s Parents
      parent: Advice
    3435952c9e7847eb844530237eefb966:
      title: Prayer for the Long Life of Khyenrab Chökyi Özer
      parent: Long Life Prayers
    2be0181908db4228877b8e8350774b3e:
      title: 'The Flower of Auspiciousness: A Prayer for the Long Life of Khenpo Khyenrab
        Chökyi Özer, Masterful Expositor of Scripture and Reasoning'
      parent: Long Life Prayers
    74e929aea147433e8de3feaa08e206cf:
      title: 'The Sweet Melody to Accomplish Words of Truth: A Prayer for the Long
        Life of the Dharma-Expounding Guide Khenchen Khyenrab Chökyi Özer'
      parent: Long Life Prayers
created_at: '2022-03-01T00:31:13.643998'
last_modified_at: '2022-03-01T00:31:13.644000'
